// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/todo_service.proto

package io.github.viqueen.todo.v1;

/**
 * Protobuf type {@code todo.v1.CreateResponse}
 */
public  final class CreateResponse extends
    com.google.protobuf.GeneratedMessageLite<
        CreateResponse, CreateResponse.Builder> implements
    // @@protoc_insertion_point(message_implements:todo.v1.CreateResponse)
    CreateResponseOrBuilder {
  private CreateResponse() {
  }
  public static final int TODO_FIELD_NUMBER = 1;
  private io.github.viqueen.todo.v1.Todo todo_;
  /**
   * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
   */
  @java.lang.Override
  public boolean hasTodo() {
    return todo_ != null;
  }
  /**
   * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
   */
  @java.lang.Override
  public io.github.viqueen.todo.v1.Todo getTodo() {
    return todo_ == null ? io.github.viqueen.todo.v1.Todo.getDefaultInstance() : todo_;
  }
  /**
   * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
   */
  private void setTodo(io.github.viqueen.todo.v1.Todo value) {
    value.getClass();
  todo_ = value;
    
    }
  /**
   * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeTodo(io.github.viqueen.todo.v1.Todo value) {
    value.getClass();
  if (todo_ != null &&
        todo_ != io.github.viqueen.todo.v1.Todo.getDefaultInstance()) {
      todo_ =
        io.github.viqueen.todo.v1.Todo.newBuilder(todo_).mergeFrom(value).buildPartial();
    } else {
      todo_ = value;
    }
    
  }
  /**
   * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
   */
  private void clearTodo() {  todo_ = null;
    
  }

  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.CreateResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.github.viqueen.todo.v1.CreateResponse prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code todo.v1.CreateResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.github.viqueen.todo.v1.CreateResponse, Builder> implements
      // @@protoc_insertion_point(builder_implements:todo.v1.CreateResponse)
      io.github.viqueen.todo.v1.CreateResponseOrBuilder {
    // Construct using io.github.viqueen.todo.v1.CreateResponse.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
     */
    @java.lang.Override
    public boolean hasTodo() {
      return instance.hasTodo();
    }
    /**
     * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
     */
    @java.lang.Override
    public io.github.viqueen.todo.v1.Todo getTodo() {
      return instance.getTodo();
    }
    /**
     * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
     */
    public Builder setTodo(io.github.viqueen.todo.v1.Todo value) {
      copyOnWrite();
      instance.setTodo(value);
      return this;
      }
    /**
     * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
     */
    public Builder setTodo(
        io.github.viqueen.todo.v1.Todo.Builder builderForValue) {
      copyOnWrite();
      instance.setTodo(builderForValue.build());
      return this;
    }
    /**
     * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
     */
    public Builder mergeTodo(io.github.viqueen.todo.v1.Todo value) {
      copyOnWrite();
      instance.mergeTodo(value);
      return this;
    }
    /**
     * <code>.todo.v1.Todo todo = 1 [json_name = "todo"];</code>
     */
    public Builder clearTodo() {  copyOnWrite();
      instance.clearTodo();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:todo.v1.CreateResponse)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.github.viqueen.todo.v1.CreateResponse();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "todo_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.github.viqueen.todo.v1.CreateResponse> parser = PARSER;
        if (parser == null) {
          synchronized (io.github.viqueen.todo.v1.CreateResponse.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.github.viqueen.todo.v1.CreateResponse>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:todo.v1.CreateResponse)
  private static final io.github.viqueen.todo.v1.CreateResponse DEFAULT_INSTANCE;
  static {
    CreateResponse defaultInstance = new CreateResponse();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      CreateResponse.class, defaultInstance);
  }

  public static io.github.viqueen.todo.v1.CreateResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<CreateResponse> PARSER;

  public static com.google.protobuf.Parser<CreateResponse> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

