// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/todo_service.proto

// Protobuf Java Version: 4.26.1
package io.github.viqueen.todo.v1;

public interface ListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.ListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  java.util.List<io.github.viqueen.todo.v1.Todo> 
      getTodosList();
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  io.github.viqueen.todo.v1.Todo getTodos(int index);
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  int getTodosCount();
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  java.util.List<? extends io.github.viqueen.todo.v1.TodoOrBuilder> 
      getTodosOrBuilderList();
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  io.github.viqueen.todo.v1.TodoOrBuilder getTodosOrBuilder(
      int index);
}
