// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/todo_service.proto

// Protobuf Java Version: 4.26.1
package io.github.viqueen.todo.v1;

/**
 * Protobuf type {@code todo.v1.ListResponse}
 */
public final class ListResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:todo.v1.ListResponse)
    ListResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      ListResponse.class.getName());
  }
  // Use ListResponse.newBuilder() to construct.
  private ListResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListResponse() {
    todos_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.github.viqueen.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_ListResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.github.viqueen.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_ListResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.github.viqueen.todo.v1.ListResponse.class, io.github.viqueen.todo.v1.ListResponse.Builder.class);
  }

  public static final int TODOS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.github.viqueen.todo.v1.Todo> todos_;
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  @java.lang.Override
  public java.util.List<io.github.viqueen.todo.v1.Todo> getTodosList() {
    return todos_;
  }
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.github.viqueen.todo.v1.TodoOrBuilder> 
      getTodosOrBuilderList() {
    return todos_;
  }
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  @java.lang.Override
  public int getTodosCount() {
    return todos_.size();
  }
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  @java.lang.Override
  public io.github.viqueen.todo.v1.Todo getTodos(int index) {
    return todos_.get(index);
  }
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  @java.lang.Override
  public io.github.viqueen.todo.v1.TodoOrBuilder getTodosOrBuilder(
      int index) {
    return todos_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < todos_.size(); i++) {
      output.writeMessage(1, todos_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < todos_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, todos_.get(i));
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.github.viqueen.todo.v1.ListResponse)) {
      return super.equals(obj);
    }
    io.github.viqueen.todo.v1.ListResponse other = (io.github.viqueen.todo.v1.ListResponse) obj;

    if (!getTodosList()
        .equals(other.getTodosList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTodosCount() > 0) {
      hash = (37 * hash) + TODOS_FIELD_NUMBER;
      hash = (53 * hash) + getTodosList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.github.viqueen.todo.v1.ListResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.github.viqueen.todo.v1.ListResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.github.viqueen.todo.v1.ListResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.github.viqueen.todo.v1.ListResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code todo.v1.ListResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:todo.v1.ListResponse)
      io.github.viqueen.todo.v1.ListResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.github.viqueen.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_ListResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.github.viqueen.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_ListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.github.viqueen.todo.v1.ListResponse.class, io.github.viqueen.todo.v1.ListResponse.Builder.class);
    }

    // Construct using io.github.viqueen.todo.v1.ListResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (todosBuilder_ == null) {
        todos_ = java.util.Collections.emptyList();
      } else {
        todos_ = null;
        todosBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.github.viqueen.todo.v1.TodoServiceOuterClass.internal_static_todo_v1_ListResponse_descriptor;
    }

    @java.lang.Override
    public io.github.viqueen.todo.v1.ListResponse getDefaultInstanceForType() {
      return io.github.viqueen.todo.v1.ListResponse.getDefaultInstance();
    }

    @java.lang.Override
    public io.github.viqueen.todo.v1.ListResponse build() {
      io.github.viqueen.todo.v1.ListResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.github.viqueen.todo.v1.ListResponse buildPartial() {
      io.github.viqueen.todo.v1.ListResponse result = new io.github.viqueen.todo.v1.ListResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.github.viqueen.todo.v1.ListResponse result) {
      if (todosBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          todos_ = java.util.Collections.unmodifiableList(todos_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.todos_ = todos_;
      } else {
        result.todos_ = todosBuilder_.build();
      }
    }

    private void buildPartial0(io.github.viqueen.todo.v1.ListResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.github.viqueen.todo.v1.ListResponse) {
        return mergeFrom((io.github.viqueen.todo.v1.ListResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.github.viqueen.todo.v1.ListResponse other) {
      if (other == io.github.viqueen.todo.v1.ListResponse.getDefaultInstance()) return this;
      if (todosBuilder_ == null) {
        if (!other.todos_.isEmpty()) {
          if (todos_.isEmpty()) {
            todos_ = other.todos_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTodosIsMutable();
            todos_.addAll(other.todos_);
          }
          onChanged();
        }
      } else {
        if (!other.todos_.isEmpty()) {
          if (todosBuilder_.isEmpty()) {
            todosBuilder_.dispose();
            todosBuilder_ = null;
            todos_ = other.todos_;
            bitField0_ = (bitField0_ & ~0x00000001);
            todosBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 getTodosFieldBuilder() : null;
          } else {
            todosBuilder_.addAllMessages(other.todos_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.github.viqueen.todo.v1.Todo m =
                  input.readMessage(
                      io.github.viqueen.todo.v1.Todo.parser(),
                      extensionRegistry);
              if (todosBuilder_ == null) {
                ensureTodosIsMutable();
                todos_.add(m);
              } else {
                todosBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.github.viqueen.todo.v1.Todo> todos_ =
      java.util.Collections.emptyList();
    private void ensureTodosIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        todos_ = new java.util.ArrayList<io.github.viqueen.todo.v1.Todo>(todos_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.viqueen.todo.v1.Todo, io.github.viqueen.todo.v1.Todo.Builder, io.github.viqueen.todo.v1.TodoOrBuilder> todosBuilder_;

    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public java.util.List<io.github.viqueen.todo.v1.Todo> getTodosList() {
      if (todosBuilder_ == null) {
        return java.util.Collections.unmodifiableList(todos_);
      } else {
        return todosBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public int getTodosCount() {
      if (todosBuilder_ == null) {
        return todos_.size();
      } else {
        return todosBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public io.github.viqueen.todo.v1.Todo getTodos(int index) {
      if (todosBuilder_ == null) {
        return todos_.get(index);
      } else {
        return todosBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder setTodos(
        int index, io.github.viqueen.todo.v1.Todo value) {
      if (todosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTodosIsMutable();
        todos_.set(index, value);
        onChanged();
      } else {
        todosBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder setTodos(
        int index, io.github.viqueen.todo.v1.Todo.Builder builderForValue) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.set(index, builderForValue.build());
        onChanged();
      } else {
        todosBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder addTodos(io.github.viqueen.todo.v1.Todo value) {
      if (todosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTodosIsMutable();
        todos_.add(value);
        onChanged();
      } else {
        todosBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder addTodos(
        int index, io.github.viqueen.todo.v1.Todo value) {
      if (todosBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTodosIsMutable();
        todos_.add(index, value);
        onChanged();
      } else {
        todosBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder addTodos(
        io.github.viqueen.todo.v1.Todo.Builder builderForValue) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.add(builderForValue.build());
        onChanged();
      } else {
        todosBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder addTodos(
        int index, io.github.viqueen.todo.v1.Todo.Builder builderForValue) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.add(index, builderForValue.build());
        onChanged();
      } else {
        todosBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder addAllTodos(
        java.lang.Iterable<? extends io.github.viqueen.todo.v1.Todo> values) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, todos_);
        onChanged();
      } else {
        todosBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder clearTodos() {
      if (todosBuilder_ == null) {
        todos_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        todosBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public Builder removeTodos(int index) {
      if (todosBuilder_ == null) {
        ensureTodosIsMutable();
        todos_.remove(index);
        onChanged();
      } else {
        todosBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public io.github.viqueen.todo.v1.Todo.Builder getTodosBuilder(
        int index) {
      return getTodosFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public io.github.viqueen.todo.v1.TodoOrBuilder getTodosOrBuilder(
        int index) {
      if (todosBuilder_ == null) {
        return todos_.get(index);  } else {
        return todosBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public java.util.List<? extends io.github.viqueen.todo.v1.TodoOrBuilder> 
         getTodosOrBuilderList() {
      if (todosBuilder_ != null) {
        return todosBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(todos_);
      }
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public io.github.viqueen.todo.v1.Todo.Builder addTodosBuilder() {
      return getTodosFieldBuilder().addBuilder(
          io.github.viqueen.todo.v1.Todo.getDefaultInstance());
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public io.github.viqueen.todo.v1.Todo.Builder addTodosBuilder(
        int index) {
      return getTodosFieldBuilder().addBuilder(
          index, io.github.viqueen.todo.v1.Todo.getDefaultInstance());
    }
    /**
     * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
     */
    public java.util.List<io.github.viqueen.todo.v1.Todo.Builder> 
         getTodosBuilderList() {
      return getTodosFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.github.viqueen.todo.v1.Todo, io.github.viqueen.todo.v1.Todo.Builder, io.github.viqueen.todo.v1.TodoOrBuilder> 
        getTodosFieldBuilder() {
      if (todosBuilder_ == null) {
        todosBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.github.viqueen.todo.v1.Todo, io.github.viqueen.todo.v1.Todo.Builder, io.github.viqueen.todo.v1.TodoOrBuilder>(
                todos_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        todos_ = null;
      }
      return todosBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:todo.v1.ListResponse)
  }

  // @@protoc_insertion_point(class_scope:todo.v1.ListResponse)
  private static final io.github.viqueen.todo.v1.ListResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.github.viqueen.todo.v1.ListResponse();
  }

  public static io.github.viqueen.todo.v1.ListResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListResponse>() {
    @java.lang.Override
    public ListResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.github.viqueen.todo.v1.ListResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

