// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/models.proto
// Protobuf Java Version: 4.26.1

package io.github.viqueen.todo.v1;

public final class Models {
  private Models() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      Models.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_Todo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_Todo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024todo/v1/models.proto\022\007todo.v1\"V\n\004Todo\022" +
      "\016\n\002id\030\001 \001(\tR\002id\022 \n\013description\030\002 \001(\tR\013de" +
      "scription\022\034\n\tcompleted\030\003 \001(\010R\tcompletedB" +
      "^\n\031io.github.viqueen.todo.v1P\001Z?github.c" +
      "om/viqueen/monorepo-template/_api/go-sdk" +
      "/todo/v1;todoV1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_todo_v1_Todo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_todo_v1_Todo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_Todo_descriptor,
        new java.lang.String[] { "Id", "Description", "Completed", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
