// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/todo_service.proto
// Protobuf Java Version: 4.26.1

package io.github.viqueen.todo.v1;

public final class TodoServiceOuterClass {
  private TodoServiceOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 1,
      /* suffix= */ "",
      TodoServiceOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_CreateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_CreateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_CreateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_CreateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_ReadRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_ReadRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_ReadResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_ReadResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_UpdateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_UpdateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_UpdateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_UpdateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_DeleteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_DeleteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_DeleteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_DeleteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_ListRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_ListRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_todo_v1_ListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_todo_v1_ListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032todo/v1/todo_service.proto\022\007todo.v1\032\024t" +
      "odo/v1/models.proto\"2\n\rCreateRequest\022!\n\004" +
      "todo\030\001 \001(\0132\r.todo.v1.TodoR\004todo\"3\n\016Creat" +
      "eResponse\022!\n\004todo\030\001 \001(\0132\r.todo.v1.TodoR\004" +
      "todo\"\035\n\013ReadRequest\022\016\n\002id\030\001 \001(\tR\002id\"1\n\014R" +
      "eadResponse\022!\n\004todo\030\001 \001(\0132\r.todo.v1.Todo" +
      "R\004todo\"2\n\rUpdateRequest\022!\n\004todo\030\001 \001(\0132\r." +
      "todo.v1.TodoR\004todo\"3\n\016UpdateResponse\022!\n\004" +
      "todo\030\001 \001(\0132\r.todo.v1.TodoR\004todo\"\037\n\rDelet" +
      "eRequest\022\016\n\002id\030\001 \001(\tR\002id\"3\n\016DeleteRespon" +
      "se\022!\n\004todo\030\001 \001(\0132\r.todo.v1.TodoR\004todo\"\r\n" +
      "\013ListRequest\"3\n\014ListResponse\022#\n\005todos\030\001 " +
      "\003(\0132\r.todo.v1.TodoR\005todos2\250\002\n\013TodoServic" +
      "e\0229\n\006Create\022\026.todo.v1.CreateRequest\032\027.to" +
      "do.v1.CreateResponse\0223\n\004Read\022\024.todo.v1.R" +
      "eadRequest\032\025.todo.v1.ReadResponse\0229\n\006Upd" +
      "ate\022\026.todo.v1.UpdateRequest\032\027.todo.v1.Up" +
      "dateResponse\0229\n\006Delete\022\026.todo.v1.DeleteR" +
      "equest\032\027.todo.v1.DeleteResponse\0223\n\004List\022" +
      "\024.todo.v1.ListRequest\032\025.todo.v1.ListResp" +
      "onseB^\n\031io.github.viqueen.todo.v1P\001Z?git" +
      "hub.com/viqueen/monorepo-template/_api/g" +
      "o-sdk/todo/v1;todoV1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          io.github.viqueen.todo.v1.Models.getDescriptor(),
        });
    internal_static_todo_v1_CreateRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_todo_v1_CreateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_CreateRequest_descriptor,
        new java.lang.String[] { "Todo", });
    internal_static_todo_v1_CreateResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_todo_v1_CreateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_CreateResponse_descriptor,
        new java.lang.String[] { "Todo", });
    internal_static_todo_v1_ReadRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_todo_v1_ReadRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_ReadRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_todo_v1_ReadResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_todo_v1_ReadResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_ReadResponse_descriptor,
        new java.lang.String[] { "Todo", });
    internal_static_todo_v1_UpdateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_todo_v1_UpdateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_UpdateRequest_descriptor,
        new java.lang.String[] { "Todo", });
    internal_static_todo_v1_UpdateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_todo_v1_UpdateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_UpdateResponse_descriptor,
        new java.lang.String[] { "Todo", });
    internal_static_todo_v1_DeleteRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_todo_v1_DeleteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_DeleteRequest_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_todo_v1_DeleteResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_todo_v1_DeleteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_DeleteResponse_descriptor,
        new java.lang.String[] { "Todo", });
    internal_static_todo_v1_ListRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_todo_v1_ListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_ListRequest_descriptor,
        new java.lang.String[] { });
    internal_static_todo_v1_ListResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_todo_v1_ListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_todo_v1_ListResponse_descriptor,
        new java.lang.String[] { "Todos", });
    descriptor.resolveAllFeaturesImmutable();
    io.github.viqueen.todo.v1.Models.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
