// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/models.proto

// Protobuf Java Version: 4.26.1
package io.github.viqueen.todo.v1;

public interface TodoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.Todo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool completed = 3 [json_name = "completed"];</code>
   * @return The completed.
   */
  boolean getCompleted();
}
