// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        (unknown)
// source: todo/v1/models.proto

package todoV1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Todo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Completed   bool   `protobuf:"varint,3,opt,name=completed,proto3" json:"completed,omitempty"`
	// Types that are assignable to Type:
	//
	//	*Todo_Simple
	//	*Todo_Advanced
	Type isTodo_Type `protobuf_oneof:"type"`
}

func (x *Todo) Reset() {
	*x = Todo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_v1_models_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Todo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Todo) ProtoMessage() {}

func (x *Todo) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_models_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Todo.ProtoReflect.Descriptor instead.
func (*Todo) Descriptor() ([]byte, []int) {
	return file_todo_v1_models_proto_rawDescGZIP(), []int{0}
}

func (x *Todo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Todo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Todo) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (m *Todo) GetType() isTodo_Type {
	if m != nil {
		return m.Type
	}
	return nil
}

func (x *Todo) GetSimple() *SimpleType {
	if x, ok := x.GetType().(*Todo_Simple); ok {
		return x.Simple
	}
	return nil
}

func (x *Todo) GetAdvanced() *AdvancedType {
	if x, ok := x.GetType().(*Todo_Advanced); ok {
		return x.Advanced
	}
	return nil
}

type isTodo_Type interface {
	isTodo_Type()
}

type Todo_Simple struct {
	Simple *SimpleType `protobuf:"bytes,4,opt,name=simple,proto3,oneof"`
}

type Todo_Advanced struct {
	Advanced *AdvancedType `protobuf:"bytes,5,opt,name=advanced,proto3,oneof"`
}

func (*Todo_Simple) isTodo_Type() {}

func (*Todo_Advanced) isTodo_Type() {}

type SimpleType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
}

func (x *SimpleType) Reset() {
	*x = SimpleType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_v1_models_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SimpleType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimpleType) ProtoMessage() {}

func (x *SimpleType) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_models_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimpleType.ProtoReflect.Descriptor instead.
func (*SimpleType) Descriptor() ([]byte, []int) {
	return file_todo_v1_models_proto_rawDescGZIP(), []int{1}
}

func (x *SimpleType) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

type AdvancedType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tag       string `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
}

func (x *AdvancedType) Reset() {
	*x = AdvancedType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todo_v1_models_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AdvancedType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdvancedType) ProtoMessage() {}

func (x *AdvancedType) ProtoReflect() protoreflect.Message {
	mi := &file_todo_v1_models_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdvancedType.ProtoReflect.Descriptor instead.
func (*AdvancedType) Descriptor() ([]byte, []int) {
	return file_todo_v1_models_proto_rawDescGZIP(), []int{2}
}

func (x *AdvancedType) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *AdvancedType) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

var File_todo_v1_models_proto protoreflect.FileDescriptor

var file_todo_v1_models_proto_rawDesc = []byte{
	0x0a, 0x14, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x76, 0x31, 0x22,
	0xc2, 0x01, 0x0a, 0x04, 0x54, 0x6f, 0x64, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x09, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x48, 0x00, 0x52,
	0x06, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x33, 0x0a, 0x08, 0x61, 0x64, 0x76, 0x61, 0x6e,
	0x63, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x74, 0x6f, 0x64, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x54, 0x79, 0x70, 0x65,
	0x48, 0x00, 0x52, 0x08, 0x61, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64, 0x42, 0x06, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x22, 0x1e, 0x0a, 0x0a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x74, 0x61, 0x67, 0x22, 0x3e, 0x0a, 0x0c, 0x41, 0x64, 0x76, 0x61, 0x6e, 0x63, 0x65, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x42, 0x5e, 0x0a, 0x19, 0x69, 0x6f, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x76, 0x69, 0x71, 0x75, 0x65, 0x65, 0x6e, 0x2e, 0x74, 0x6f, 0x64, 0x6f, 0x2e, 0x76,
	0x31, 0x50, 0x01, 0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x76, 0x69, 0x71, 0x75, 0x65, 0x65, 0x6e, 0x2f, 0x6d, 0x6f, 0x6e, 0x6f, 0x72, 0x65, 0x70, 0x6f,
	0x2d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x2f, 0x5f, 0x61, 0x70, 0x69, 0x2f, 0x67,
	0x6f, 0x2d, 0x73, 0x64, 0x6b, 0x2f, 0x74, 0x6f, 0x64, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x74, 0x6f,
	0x64, 0x6f, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_todo_v1_models_proto_rawDescOnce sync.Once
	file_todo_v1_models_proto_rawDescData = file_todo_v1_models_proto_rawDesc
)

func file_todo_v1_models_proto_rawDescGZIP() []byte {
	file_todo_v1_models_proto_rawDescOnce.Do(func() {
		file_todo_v1_models_proto_rawDescData = protoimpl.X.CompressGZIP(file_todo_v1_models_proto_rawDescData)
	})
	return file_todo_v1_models_proto_rawDescData
}

var file_todo_v1_models_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_todo_v1_models_proto_goTypes = []interface{}{
	(*Todo)(nil),         // 0: todo.v1.Todo
	(*SimpleType)(nil),   // 1: todo.v1.SimpleType
	(*AdvancedType)(nil), // 2: todo.v1.AdvancedType
}
var file_todo_v1_models_proto_depIdxs = []int32{
	1, // 0: todo.v1.Todo.simple:type_name -> todo.v1.SimpleType
	2, // 1: todo.v1.Todo.advanced:type_name -> todo.v1.AdvancedType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_todo_v1_models_proto_init() }
func file_todo_v1_models_proto_init() {
	if File_todo_v1_models_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todo_v1_models_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Todo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_v1_models_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SimpleType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todo_v1_models_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AdvancedType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_todo_v1_models_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*Todo_Simple)(nil),
		(*Todo_Advanced)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todo_v1_models_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_todo_v1_models_proto_goTypes,
		DependencyIndexes: file_todo_v1_models_proto_depIdxs,
		MessageInfos:      file_todo_v1_models_proto_msgTypes,
	}.Build()
	File_todo_v1_models_proto = out.File
	file_todo_v1_models_proto_rawDesc = nil
	file_todo_v1_models_proto_goTypes = nil
	file_todo_v1_models_proto_depIdxs = nil
}
