// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/admin/v1/admin_todo_service.proto

package io.github.viqueen.todo.admin.v1;

public final class AdminTodoServiceOuterClass {
  private AdminTodoServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
