// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/admin/v1/admin_todo_service.proto

package io.github.viqueen.todo.admin.v1;

public interface ListTodosResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.admin.v1.ListTodosResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  java.util.List<io.github.viqueen.todo.v1.Todo> 
      getTodosList();
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  io.github.viqueen.todo.v1.Todo getTodos(int index);
  /**
   * <code>repeated .todo.v1.Todo todos = 1 [json_name = "todos"];</code>
   */
  int getTodosCount();
}
