// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/admin/v1/admin_todo_service.proto

package io.github.viqueen.todo.admin.v1;

/**
 * Protobuf type {@code todo.admin.v1.ListTodosRequest}
 */
public  final class ListTodosRequest extends
    com.google.protobuf.GeneratedMessageLite<
        ListTodosRequest, ListTodosRequest.Builder> implements
    // @@protoc_insertion_point(message_implements:todo.admin.v1.ListTodosRequest)
    ListTodosRequestOrBuilder {
  private ListTodosRequest() {
    query_ = "";
  }
  public static final int QUERY_FIELD_NUMBER = 1;
  private java.lang.String query_;
  /**
   * <code>string query = 1 [json_name = "query"];</code>
   * @return The query.
   */
  @java.lang.Override
  public java.lang.String getQuery() {
    return query_;
  }
  /**
   * <code>string query = 1 [json_name = "query"];</code>
   * @return The bytes for query.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getQueryBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(query_);
  }
  /**
   * <code>string query = 1 [json_name = "query"];</code>
   * @param value The query to set.
   */
  private void setQuery(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    query_ = value;
  }
  /**
   * <code>string query = 1 [json_name = "query"];</code>
   */
  private void clearQuery() {
    
    query_ = getDefaultInstance().getQuery();
  }
  /**
   * <code>string query = 1 [json_name = "query"];</code>
   * @param value The bytes for query to set.
   */
  private void setQueryBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    query_ = value.toStringUtf8();
    
  }

  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.admin.v1.ListTodosRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.github.viqueen.todo.admin.v1.ListTodosRequest prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code todo.admin.v1.ListTodosRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.github.viqueen.todo.admin.v1.ListTodosRequest, Builder> implements
      // @@protoc_insertion_point(builder_implements:todo.admin.v1.ListTodosRequest)
      io.github.viqueen.todo.admin.v1.ListTodosRequestOrBuilder {
    // Construct using io.github.viqueen.todo.admin.v1.ListTodosRequest.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @return The query.
     */
    @java.lang.Override
    public java.lang.String getQuery() {
      return instance.getQuery();
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @return The bytes for query.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getQueryBytes() {
      return instance.getQueryBytes();
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @param value The query to set.
     * @return This builder for chaining.
     */
    public Builder setQuery(
        java.lang.String value) {
      copyOnWrite();
      instance.setQuery(value);
      return this;
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @return This builder for chaining.
     */
    public Builder clearQuery() {
      copyOnWrite();
      instance.clearQuery();
      return this;
    }
    /**
     * <code>string query = 1 [json_name = "query"];</code>
     * @param value The bytes for query to set.
     * @return This builder for chaining.
     */
    public Builder setQueryBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setQueryBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:todo.admin.v1.ListTodosRequest)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.github.viqueen.todo.admin.v1.ListTodosRequest();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "query_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.github.viqueen.todo.admin.v1.ListTodosRequest> parser = PARSER;
        if (parser == null) {
          synchronized (io.github.viqueen.todo.admin.v1.ListTodosRequest.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.github.viqueen.todo.admin.v1.ListTodosRequest>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:todo.admin.v1.ListTodosRequest)
  private static final io.github.viqueen.todo.admin.v1.ListTodosRequest DEFAULT_INSTANCE;
  static {
    ListTodosRequest defaultInstance = new ListTodosRequest();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListTodosRequest.class, defaultInstance);
  }

  public static io.github.viqueen.todo.admin.v1.ListTodosRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListTodosRequest> PARSER;

  public static com.google.protobuf.Parser<ListTodosRequest> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

