// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/admin/v1/admin_todo_service.proto

package io.github.viqueen.todo.admin.v1;

public interface ListTodosRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.admin.v1.ListTodosRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string query = 1 [json_name = "query"];</code>
   * @return The query.
   */
  java.lang.String getQuery();
  /**
   * <code>string query = 1 [json_name = "query"];</code>
   * @return The bytes for query.
   */
  com.google.protobuf.ByteString
      getQueryBytes();
}
