// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: todo/v1/todo_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.viqueen.todo.v1;

@kotlin.jvm.JvmName("-initializelistRequest")
public inline fun listRequest(block: io.github.viqueen.todo.v1.ListRequestKt.Dsl.() -> kotlin.Unit): io.github.viqueen.todo.v1.ListRequest =
  io.github.viqueen.todo.v1.ListRequestKt.Dsl._create(io.github.viqueen.todo.v1.ListRequest.newBuilder()).apply { block() }._build()
/**
 * Protobuf type `todo.v1.ListRequest`
 */
public object ListRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: io.github.viqueen.todo.v1.ListRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: io.github.viqueen.todo.v1.ListRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): io.github.viqueen.todo.v1.ListRequest = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun io.github.viqueen.todo.v1.ListRequest.copy(block: `io.github.viqueen.todo.v1`.ListRequestKt.Dsl.() -> kotlin.Unit): io.github.viqueen.todo.v1.ListRequest =
  `io.github.viqueen.todo.v1`.ListRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

