// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: todo/v1/todo_service.proto

// Generated files should ignore deprecation warnings
@file:Suppress("DEPRECATION")
package io.github.viqueen.todo.v1;

