// @generated by protoc-gen-connect-es v1.4.0 with parameter "target=ts"
// @generated from file todo/admin/v1/admin_todo_service.proto (package todo.admin.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { ListTodosRequest, ListTodosResponse } from "./admin_todo_service_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service todo.admin.v1.AdminTodoService
 */
export const AdminTodoService = {
  typeName: "todo.admin.v1.AdminTodoService",
  methods: {
    /**
     * @generated from rpc todo.admin.v1.AdminTodoService.ListTodos
     */
    listTodos: {
      name: "ListTodos",
      I: ListTodosRequest,
      O: ListTodosResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

