// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/models.proto

package io.github.viqueen.todo.v1;

/**
 * Protobuf type {@code todo.v1.AdvancedType}
 */
public  final class AdvancedType extends
    com.google.protobuf.GeneratedMessageLite<
        AdvancedType, AdvancedType.Builder> implements
    // @@protoc_insertion_point(message_implements:todo.v1.AdvancedType)
    AdvancedTypeOrBuilder {
  private AdvancedType() {
    tag_ = "";
    namespace_ = "";
  }
  public static final int TAG_FIELD_NUMBER = 1;
  private java.lang.String tag_;
  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @return The tag.
   */
  @java.lang.Override
  public java.lang.String getTag() {
    return tag_;
  }
  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTagBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(tag_);
  }
  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @param value The tag to set.
   */
  private void setTag(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    tag_ = value;
  }
  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   */
  private void clearTag() {
    
    tag_ = getDefaultInstance().getTag();
  }
  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @param value The bytes for tag to set.
   */
  private void setTagBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    tag_ = value.toStringUtf8();
    
  }

  public static final int NAMESPACE_FIELD_NUMBER = 2;
  private java.lang.String namespace_;
  /**
   * <code>string namespace = 2 [json_name = "namespace"];</code>
   * @return The namespace.
   */
  @java.lang.Override
  public java.lang.String getNamespace() {
    return namespace_;
  }
  /**
   * <code>string namespace = 2 [json_name = "namespace"];</code>
   * @return The bytes for namespace.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(namespace_);
  }
  /**
   * <code>string namespace = 2 [json_name = "namespace"];</code>
   * @param value The namespace to set.
   */
  private void setNamespace(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    namespace_ = value;
  }
  /**
   * <code>string namespace = 2 [json_name = "namespace"];</code>
   */
  private void clearNamespace() {
    
    namespace_ = getDefaultInstance().getNamespace();
  }
  /**
   * <code>string namespace = 2 [json_name = "namespace"];</code>
   * @param value The bytes for namespace to set.
   */
  private void setNamespaceBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    namespace_ = value.toStringUtf8();
    
  }

  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.AdvancedType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.github.viqueen.todo.v1.AdvancedType prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code todo.v1.AdvancedType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.github.viqueen.todo.v1.AdvancedType, Builder> implements
      // @@protoc_insertion_point(builder_implements:todo.v1.AdvancedType)
      io.github.viqueen.todo.v1.AdvancedTypeOrBuilder {
    // Construct using io.github.viqueen.todo.v1.AdvancedType.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>string tag = 1 [json_name = "tag"];</code>
     * @return The tag.
     */
    @java.lang.Override
    public java.lang.String getTag() {
      return instance.getTag();
    }
    /**
     * <code>string tag = 1 [json_name = "tag"];</code>
     * @return The bytes for tag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagBytes() {
      return instance.getTagBytes();
    }
    /**
     * <code>string tag = 1 [json_name = "tag"];</code>
     * @param value The tag to set.
     * @return This builder for chaining.
     */
    public Builder setTag(
        java.lang.String value) {
      copyOnWrite();
      instance.setTag(value);
      return this;
    }
    /**
     * <code>string tag = 1 [json_name = "tag"];</code>
     * @return This builder for chaining.
     */
    public Builder clearTag() {
      copyOnWrite();
      instance.clearTag();
      return this;
    }
    /**
     * <code>string tag = 1 [json_name = "tag"];</code>
     * @param value The bytes for tag to set.
     * @return This builder for chaining.
     */
    public Builder setTagBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setTagBytes(value);
      return this;
    }

    /**
     * <code>string namespace = 2 [json_name = "namespace"];</code>
     * @return The namespace.
     */
    @java.lang.Override
    public java.lang.String getNamespace() {
      return instance.getNamespace();
    }
    /**
     * <code>string namespace = 2 [json_name = "namespace"];</code>
     * @return The bytes for namespace.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      return instance.getNamespaceBytes();
    }
    /**
     * <code>string namespace = 2 [json_name = "namespace"];</code>
     * @param value The namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespace(
        java.lang.String value) {
      copyOnWrite();
      instance.setNamespace(value);
      return this;
    }
    /**
     * <code>string namespace = 2 [json_name = "namespace"];</code>
     * @return This builder for chaining.
     */
    public Builder clearNamespace() {
      copyOnWrite();
      instance.clearNamespace();
      return this;
    }
    /**
     * <code>string namespace = 2 [json_name = "namespace"];</code>
     * @param value The bytes for namespace to set.
     * @return This builder for chaining.
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNamespaceBytes(value);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:todo.v1.AdvancedType)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.github.viqueen.todo.v1.AdvancedType();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "tag_",
            "namespace_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.github.viqueen.todo.v1.AdvancedType> parser = PARSER;
        if (parser == null) {
          synchronized (io.github.viqueen.todo.v1.AdvancedType.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.github.viqueen.todo.v1.AdvancedType>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:todo.v1.AdvancedType)
  private static final io.github.viqueen.todo.v1.AdvancedType DEFAULT_INSTANCE;
  static {
    AdvancedType defaultInstance = new AdvancedType();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      AdvancedType.class, defaultInstance);
  }

  public static io.github.viqueen.todo.v1.AdvancedType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<AdvancedType> PARSER;

  public static com.google.protobuf.Parser<AdvancedType> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

