// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/models.proto

package io.github.viqueen.todo.v1;

public interface AdvancedTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.AdvancedType)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();

  /**
   * <code>string namespace = 2 [json_name = "namespace"];</code>
   * @return The namespace.
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 2 [json_name = "namespace"];</code>
   * @return The bytes for namespace.
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();
}
