// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/todo_service.proto

package io.github.viqueen.todo.v1;

public interface DeleteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.DeleteRequest)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
