// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/todo_service.proto

package io.github.viqueen.todo.v1;

public interface ListRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.ListRequest)
    com.google.protobuf.MessageLiteOrBuilder {
}
