// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/models.proto

package io.github.viqueen.todo.v1;

public interface SimpleTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.SimpleType)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @return The tag.
   */
  java.lang.String getTag();
  /**
   * <code>string tag = 1 [json_name = "tag"];</code>
   * @return The bytes for tag.
   */
  com.google.protobuf.ByteString
      getTagBytes();
}
