// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/models.proto

package io.github.viqueen.todo.v1;

public interface TodoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:todo.v1.Todo)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool completed = 3 [json_name = "completed"];</code>
   * @return The completed.
   */
  boolean getCompleted();

  /**
   * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
   * @return Whether the simple field is set.
   */
  boolean hasSimple();
  /**
   * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
   * @return The simple.
   */
  io.github.viqueen.todo.v1.SimpleType getSimple();

  /**
   * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
   * @return Whether the advanced field is set.
   */
  boolean hasAdvanced();
  /**
   * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
   * @return The advanced.
   */
  io.github.viqueen.todo.v1.AdvancedType getAdvanced();

  public io.github.viqueen.todo.v1.Todo.TypeCase getTypeCase();
}
