// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: todo/v1/models.proto

package io.github.viqueen.todo.v1;

/**
 * Protobuf type {@code todo.v1.Todo}
 */
public  final class Todo extends
    com.google.protobuf.GeneratedMessageLite<
        Todo, Todo.Builder> implements
    // @@protoc_insertion_point(message_implements:todo.v1.Todo)
    TodoOrBuilder {
  private Todo() {
    id_ = "";
    description_ = "";
  }
  private int typeCase_ = 0;
  private java.lang.Object type_;
  public enum TypeCase {
    SIMPLE(4),
    ADVANCED(5),
    TYPE_NOT_SET(0);
    private final int value;
    private TypeCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TypeCase valueOf(int value) {
      return forNumber(value);
    }

    public static TypeCase forNumber(int value) {
      switch (value) {
        case 4: return SIMPLE;
        case 5: return ADVANCED;
        case 0: return TYPE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  @java.lang.Override
  public TypeCase
  getTypeCase() {
    return TypeCase.forNumber(
        typeCase_);
  }

  private void clearType() {
    typeCase_ = 0;
    type_ = null;
  }

  public static final int ID_FIELD_NUMBER = 1;
  private java.lang.String id_;
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    return id_;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(id_);
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The id to set.
   */
  private void setId(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    id_ = value;
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   */
  private void clearId() {
    
    id_ = getDefaultInstance().getId();
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @param value The bytes for id to set.
   */
  private void setIdBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    id_ = value.toStringUtf8();
    
  }

  public static final int DESCRIPTION_FIELD_NUMBER = 2;
  private java.lang.String description_;
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The description.
   */
  @java.lang.Override
  public java.lang.String getDescription() {
    return description_;
  }
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @return The bytes for description.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescriptionBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(description_);
  }
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @param value The description to set.
   */
  private void setDescription(
      java.lang.String value) {
    java.lang.Class<?> valueClass = value.getClass();
  
    description_ = value;
  }
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   */
  private void clearDescription() {
    
    description_ = getDefaultInstance().getDescription();
  }
  /**
   * <code>string description = 2 [json_name = "description"];</code>
   * @param value The bytes for description to set.
   */
  private void setDescriptionBytes(
      com.google.protobuf.ByteString value) {
    checkByteStringIsUtf8(value);
    description_ = value.toStringUtf8();
    
  }

  public static final int COMPLETED_FIELD_NUMBER = 3;
  private boolean completed_;
  /**
   * <code>bool completed = 3 [json_name = "completed"];</code>
   * @return The completed.
   */
  @java.lang.Override
  public boolean getCompleted() {
    return completed_;
  }
  /**
   * <code>bool completed = 3 [json_name = "completed"];</code>
   * @param value The completed to set.
   */
  private void setCompleted(boolean value) {
    
    completed_ = value;
  }
  /**
   * <code>bool completed = 3 [json_name = "completed"];</code>
   */
  private void clearCompleted() {
    
    completed_ = false;
  }

  public static final int SIMPLE_FIELD_NUMBER = 4;
  /**
   * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
   */
  @java.lang.Override
  public boolean hasSimple() {
    return typeCase_ == 4;
  }
  /**
   * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
   */
  @java.lang.Override
  public io.github.viqueen.todo.v1.SimpleType getSimple() {
    if (typeCase_ == 4) {
       return (io.github.viqueen.todo.v1.SimpleType) type_;
    }
    return io.github.viqueen.todo.v1.SimpleType.getDefaultInstance();
  }
  /**
   * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
   */
  private void setSimple(io.github.viqueen.todo.v1.SimpleType value) {
    value.getClass();
  type_ = value;
    typeCase_ = 4;
  }
  /**
   * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
   */
  private void mergeSimple(io.github.viqueen.todo.v1.SimpleType value) {
    value.getClass();
  if (typeCase_ == 4 &&
        type_ != io.github.viqueen.todo.v1.SimpleType.getDefaultInstance()) {
      type_ = io.github.viqueen.todo.v1.SimpleType.newBuilder((io.github.viqueen.todo.v1.SimpleType) type_)
          .mergeFrom(value).buildPartial();
    } else {
      type_ = value;
    }
    typeCase_ = 4;
  }
  /**
   * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
   */
  private void clearSimple() {
    if (typeCase_ == 4) {
      typeCase_ = 0;
      type_ = null;
    }
  }

  public static final int ADVANCED_FIELD_NUMBER = 5;
  /**
   * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
   */
  @java.lang.Override
  public boolean hasAdvanced() {
    return typeCase_ == 5;
  }
  /**
   * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
   */
  @java.lang.Override
  public io.github.viqueen.todo.v1.AdvancedType getAdvanced() {
    if (typeCase_ == 5) {
       return (io.github.viqueen.todo.v1.AdvancedType) type_;
    }
    return io.github.viqueen.todo.v1.AdvancedType.getDefaultInstance();
  }
  /**
   * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
   */
  private void setAdvanced(io.github.viqueen.todo.v1.AdvancedType value) {
    value.getClass();
  type_ = value;
    typeCase_ = 5;
  }
  /**
   * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
   */
  private void mergeAdvanced(io.github.viqueen.todo.v1.AdvancedType value) {
    value.getClass();
  if (typeCase_ == 5 &&
        type_ != io.github.viqueen.todo.v1.AdvancedType.getDefaultInstance()) {
      type_ = io.github.viqueen.todo.v1.AdvancedType.newBuilder((io.github.viqueen.todo.v1.AdvancedType) type_)
          .mergeFrom(value).buildPartial();
    } else {
      type_ = value;
    }
    typeCase_ = 5;
  }
  /**
   * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
   */
  private void clearAdvanced() {
    if (typeCase_ == 5) {
      typeCase_ = 0;
      type_ = null;
    }
  }

  public static io.github.viqueen.todo.v1.Todo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.Todo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.Todo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static io.github.viqueen.todo.v1.Todo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(io.github.viqueen.todo.v1.Todo prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code todo.v1.Todo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        io.github.viqueen.todo.v1.Todo, Builder> implements
      // @@protoc_insertion_point(builder_implements:todo.v1.Todo)
      io.github.viqueen.todo.v1.TodoOrBuilder {
    // Construct using io.github.viqueen.todo.v1.Todo.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    @java.lang.Override
    public TypeCase
        getTypeCase() {
      return instance.getTypeCase();
    }

    public Builder clearType() {
      copyOnWrite();
      instance.clearType();
      return this;
    }


    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      return instance.getId();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      return instance.getIdBytes();
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setIdBytes(value);
      return this;
    }

    /**
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      return instance.getDescription();
    }
    /**
     * <code>string description = 2 [json_name = "description"];</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      return instance.getDescriptionBytes();
    }
    /**
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The description to set.
     * @return This builder for chaining.
     */
    public Builder setDescription(
        java.lang.String value) {
      copyOnWrite();
      instance.setDescription(value);
      return this;
    }
    /**
     * <code>string description = 2 [json_name = "description"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDescription() {
      copyOnWrite();
      instance.clearDescription();
      return this;
    }
    /**
     * <code>string description = 2 [json_name = "description"];</code>
     * @param value The bytes for description to set.
     * @return This builder for chaining.
     */
    public Builder setDescriptionBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setDescriptionBytes(value);
      return this;
    }

    /**
     * <code>bool completed = 3 [json_name = "completed"];</code>
     * @return The completed.
     */
    @java.lang.Override
    public boolean getCompleted() {
      return instance.getCompleted();
    }
    /**
     * <code>bool completed = 3 [json_name = "completed"];</code>
     * @param value The completed to set.
     * @return This builder for chaining.
     */
    public Builder setCompleted(boolean value) {
      copyOnWrite();
      instance.setCompleted(value);
      return this;
    }
    /**
     * <code>bool completed = 3 [json_name = "completed"];</code>
     * @return This builder for chaining.
     */
    public Builder clearCompleted() {
      copyOnWrite();
      instance.clearCompleted();
      return this;
    }

    /**
     * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
     */
    @java.lang.Override
    public boolean hasSimple() {
      return instance.hasSimple();
    }
    /**
     * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
     */
    @java.lang.Override
    public io.github.viqueen.todo.v1.SimpleType getSimple() {
      return instance.getSimple();
    }
    /**
     * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
     */
    public Builder setSimple(io.github.viqueen.todo.v1.SimpleType value) {
      copyOnWrite();
      instance.setSimple(value);
      return this;
    }
    /**
     * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
     */
    public Builder setSimple(
        io.github.viqueen.todo.v1.SimpleType.Builder builderForValue) {
      copyOnWrite();
      instance.setSimple(builderForValue.build());
      return this;
    }
    /**
     * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
     */
    public Builder mergeSimple(io.github.viqueen.todo.v1.SimpleType value) {
      copyOnWrite();
      instance.mergeSimple(value);
      return this;
    }
    /**
     * <code>.todo.v1.SimpleType simple = 4 [json_name = "simple"];</code>
     */
    public Builder clearSimple() {
      copyOnWrite();
      instance.clearSimple();
      return this;
    }

    /**
     * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
     */
    @java.lang.Override
    public boolean hasAdvanced() {
      return instance.hasAdvanced();
    }
    /**
     * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
     */
    @java.lang.Override
    public io.github.viqueen.todo.v1.AdvancedType getAdvanced() {
      return instance.getAdvanced();
    }
    /**
     * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
     */
    public Builder setAdvanced(io.github.viqueen.todo.v1.AdvancedType value) {
      copyOnWrite();
      instance.setAdvanced(value);
      return this;
    }
    /**
     * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
     */
    public Builder setAdvanced(
        io.github.viqueen.todo.v1.AdvancedType.Builder builderForValue) {
      copyOnWrite();
      instance.setAdvanced(builderForValue.build());
      return this;
    }
    /**
     * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
     */
    public Builder mergeAdvanced(io.github.viqueen.todo.v1.AdvancedType value) {
      copyOnWrite();
      instance.mergeAdvanced(value);
      return this;
    }
    /**
     * <code>.todo.v1.AdvancedType advanced = 5 [json_name = "advanced"];</code>
     */
    public Builder clearAdvanced() {
      copyOnWrite();
      instance.clearAdvanced();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:todo.v1.Todo)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new io.github.viqueen.todo.v1.Todo();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "type_",
            "typeCase_",
            "id_",
            "description_",
            "completed_",
            io.github.viqueen.todo.v1.SimpleType.class,
            io.github.viqueen.todo.v1.AdvancedType.class,
          };
          java.lang.String info =
              "\u0000\u0005\u0001\u0000\u0001\u0005\u0005\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
              "\u0003\u0007\u0004<\u0000\u0005<\u0000";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<io.github.viqueen.todo.v1.Todo> parser = PARSER;
        if (parser == null) {
          synchronized (io.github.viqueen.todo.v1.Todo.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<io.github.viqueen.todo.v1.Todo>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:todo.v1.Todo)
  private static final io.github.viqueen.todo.v1.Todo DEFAULT_INSTANCE;
  static {
    Todo defaultInstance = new Todo();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Todo.class, defaultInstance);
  }

  public static io.github.viqueen.todo.v1.Todo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Todo> PARSER;

  public static com.google.protobuf.Parser<Todo> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

